<!-- File : bylaws	.html -->
<!DOCTYPE html>
<html>
   <head>
      <title> Reed College Student Body </title>
      <base href="/" target="_blank">
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- Importing stylesheets -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
      <link rel="stylesheet" href="https://use.typekit.net/plm3ftw.css">
      <link rel="stylesheet" href="./src/styles.css" type="text/css">
      <!-- Importing scripts -->
      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      <!-- The core Firebase JS SDK is always required and must be listed first -->
      <script src="https://www.gstatic.com/firebasejs/6.2.4/firebase-app.js"></script>
      <!-- Add Firebase products that you want to use -->
      <script src="https://www.gstatic.com/firebasejs/6.2.4/firebase-auth.js"></script>
      <script src="https://www.gstatic.com/firebasejs/6.2.4/firebase-firestore.js"></script>
      <script type="text/javascript" src="./src/app.min.js?p=refresh&t=1"></script>	
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap3.min.css" integrity="sha256-ze/OEYGcFbPRmvCnrSeKbRTtjG4vGLHXgOqsyLFTRjg=" crossorigin="anonymous" />
      <script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js" integrity="sha256-+C0A5Ilqmu4QcSPxrlGpaZxJ04VjsRjKu+G82kl5UJk=" crossorigin="anonymous"></script>
   </head>
   <body class="sin-app">
      <?php include '../pagelets/header.php'; ?>
      <section id="bylaws">
         <div class="container">
            <div class="row">
               <div class="col-0 col-md-1"></div>
               <div class="col-10 col-md-10" id="sin-bylaws" style="padding-left: 2em;">
                  <h1 class="text-center">Senate Bylaws</h1>
                  <br>
                  <div id="sin-bl-outline">
                     <div class="row">
                        <div class="col-md-6">
                           <ol class="text-center">
                              <li>Article I.<br><a href="#sin-bylaws-article1" class="rainbow-article-1">The Student Judicial Board Code</a></li>
                              <li>Article II.<br><a href="#sin-bylaws-article2" class="rainbow-article-2">Funding Procedures and Financial Policy</a></li>
                              <li>Article III.<br><a href="#sin-bylaws-article3" class="rainbow-article-3">Senate and Student Body Committees, Boards, and Managers</a></li>
                              <li>Article IV.<br><a href="#sin-bylaws-article4" class="rainbow-article-4">Student Body Elections</a></li>
                           </ol>
                        </div>
                        <div class="col-md-6">
                           <ol class="text-center">
                              <li>Article V.<br><a href="#sin-bylaws-article5" class="rainbow-article-5">The Student Committee on Academic Policy and Planning</a></li>
                              <li>Article VI.<br><a href="#sin-bylaws-article6" class="rainbow-article-6">The Student Diversity Committee</a></li>
                              <li>Article VII.<br><a href="#sin-bylaws-article7" class="rainbow-article-7">Rules and Procedures for Meetings</a></li>
                              <li>Article VIII.<br><a href="#sin-bylaws-article8" class="rainbow-article-8">Amendment and Suspension of bylaws</a></li>
                           </ol>
                        </div>
                     </div>
                  </div>
                  <div class="cdoc">
                     <p class="c194"><a name="sin-bylaws-article1">
                     <h2 class="rainbow-article-1">Article I. The Student Judicial Board Code </h2>
                     </p>
                     <p class="c35"><span class="c2">Section 1. </span><span class="c5">The Student Judicial Board Code shall establish the procedures to be followed in the selection of the Student Judicial Board, in handling Honor Cases by the Student Judicial Board, in handling appeals from Student Judicial Board actions, and in providing publicity for Honor Cases. The Student Judicial Board Code shall also set forth the responsibilities of the Student Judicial Board members and of the Student Judicial Board Chairperson. </span></p>
                     <p class="c52"><span class="c2">Section 2. </span><span class="c5">The Student Judicial Board Code may be amended by a two-thirds vote of the full Senate at an official meeting. </span></p>
                     <p class="c84"><a name="sin-bylaws-article2">
                     <h2 class="rainbow-article-2">Article II. Funding Procedures and Financial Policy </h2>
                     </p>
                     <p class="c27"><span class="c2">Section 1. Student Body Funds </span><span class="c5">The Senate shall have complete jurisdiction over all monies in the categories defined in the subsections of this section, as provided in the Community Constitution, Article I, Section 4. These monies shall comprise what are referred to within these Bylaws as &ldquo;Student Body Funds.&rdquo; </span></p>
                     <p class="c33"><span class="c2">A. General Fund </span><span class="c5">The General Fund, which is allocated from semester to semester by the Senate with the advice of the Student Body Treasurers, shall include: 1. All Student Body Fee receipts; 2. All revenues from student-managed concessions (except for Paradox Caf&eacute; revenues), and 3. Such a percentage of the interest on the Endowment as the Senate shall remand to it. </span></p>
                     <p class="c140"><span class="c2">B. Student Body Fees </span></p>
                     <p class="c120 c169"><span class="c5">1. Student Body Fees shall remain at a constant rate as defined by the previous change in fee. 2. Senate may propose changes to the Student Body fee. These changes must be approved by two-thirds (2/3) of the full Senate. Senate must then submit an outline of the proposed change to the College President and College Vice President Treasurer to be considered for the next fiscal year&rsquo;s college budget. The fee will be changed pending approval of college financial officers and the Board of Trustees. 3. The Student Body Fee shall be reevaluated at least every two (2) years, during the fall </span></p>
                     <p class="c44"><span class="c5">semester of every even-numbered year, in consideration with other sources of income, to assess the shortage or surplus of available funds. Should the reserve account reach depletion as per the Student Body Treasurers&rsquo; handbook, or the costs of the semester greatly outweigh the Student Body Fee collected that semester, the Senate may vote to review the Student Body Fee with a two-thirds vote at any time. Any proposed changes must be approved by two-thirds of the full Senate. </span></p>
                     <p class="c102"><span class="c2">C. Student Body Endowment </span></p>
                     <p class="c50"><span class="c5">1. The Student Body shall maintain an Endowment as a part of the College&rsquo;s portfolio of investments. This Endowment shall be governed by the same investment and financial policies as the balance of said portfolio, subject to the condition that all dividends, interest, or other profits made directly or indirectly on this Endowment shall remain in the financial jurisdiction of the Student Senate and its appointed representatives. The principal of the Endowment shall be considered inviolable, except if by a unanimous vote of the Student Senate and by the consent of the Student Body Treasurers drawing on the principle of the Endowment is deemed to be in the best interest of the Student Body. In all other cases the Senate is hereby enjoined from including it in its allocations. 2. The Senate and its appointed representatives shall have full authority to solicit contributions </span></p>
                     <p class="c12"><span class="c5">to the Endowment from all sources with the consent of the College&rsquo;s Development Office. Such contributions shall be processed by the Development Office. 3. The Student Body Endowment shall consist of money transferred to the Endowment upon the receipt of the student body fee at the start of a new academic year. The amount given to the endowment shall be a recommendation from the Student Body Treasury, pending a two- thirds vote of approval by the Senate.. The amount accruing to the Endowment at the start of the semester shall be tabulated and presented by the Student Body Treasurers at the beginning of the current semester&rsquo;s Funding Hell. 4. Donors may request, but not require, that monies contributed to the Endowment be put </span></p>
                     <p class="c90"><span class="c5">toward a specific Senate project or student-oriented program run by Reed College. Monies earmarked in such a way may be allocated in lieu of, or in addition to, monies allocated by the Senate. All allocations will ultimately be determined by the discretion of the Senate and the Treasury. 5. The average interest earned by the Student Government&rsquo;s corpus in the Reed College </span></p>
                     <p class="c54"><span class="c5">Endowment over the past five years will be allocated to the Student Opportunity Subsidy Committee (SOS) and its related programs in the current year. If the funding is excessive for the goals of the SOS, the Student Senate can divert any amount of funding they deem appropriate, with a two thirds vote, towards other Senate or student activities. If the interest is insufficient to fund the goals of the SOS Committee the Senate may increase the amount of funding given to the program one time per semester after counsel with the SOS Program Chair and Student Body Treasurers. After soliciting feedback and suggestions from the Student Body during the previous Spring semester and over the summer, SOS programs will be determined by the Senate and Treasury during the beginning of the Fall semester, and will be administered throughout the academic year. Logistics of implementation must be determined before presenting a motion to allocate funds to a specific SOS program. Each SOS allocation will require a majority approval of the Senate before implementation. If a majority approval of the Senate cannot be reached, the monies allocated to the SOS program will be rolled back into the Endowment, and the Senate will revisit the discussion of SOS program proposals at the beginning of the Spring Semester. Any unspent allocations to SOS programs will be rolled back into the Endowment. 6. The SOS model is structured to create programs offered broadly to the student body, </span></p>
                     <p class="c144"><span class="c5">sometimes in which funds may be accessed through a formal application or proposal process. Examples of potential SOS programs may include, but are not limited to: higher stipends for student body appointed and elected leadership positions for students who require further financial support to engage in these positions; funding for unpaid internships, creative projects, or other professional opportunities for students; and/or capital </span></p>
                     <p class="c98"><span class="c5">improvements to student-maintained spaces. The Senate may propose a SOS program with a total duration longer than a single academic year, but the length of a single SOS program may not exceed four semesters or expenditures of over $5,000. If a SOS program is ineffective, the Senate may vote to discontinue the program at any time, as determined by a two-thirds approval of the Senate. If a SOS program with a duration of over two semesters is ineffective, a majority approval of the Senate can discontinue the designated SOS at any time after the first two semesters. At the end of the proposed duration of a SOS program, the Senate may choose to renew or discontinue the allocation of money to that SOS program, determined by a majority approval of the Senate. Successful SOS programs may be institutionalized through additions or changes to the Student Senate Bylaws, with funding drawn from the general budget. 7. The SOS Program Chair will work in conjunction with the Treasury to draft a yearly written </span></p>
                     <p class="c133"><span class="c5">report, authored by the Senate and publicly distributed to the Reed Community at the end of each Spring semester. This written report will also include a summary of the revenue from student body fees, size of and changes to the Endowment for Student Autonomy, and expenditures from Funding Poll, Top 40 and Finance Committee. A condensed version of the report and the summary of Student Body finances will be published in The Quest. To preserve institutional memory within the Senate, the reports of the SOS programs and the details of their implementation will also be cataloged in the Senate Handbook, along with the entirety of the report. </span></p>
                     <p class="c66"><span class="c2">D. Student Body Payroll </span></p>
                     <p class="c72"><span class="c5">1. The Senate shall have authority to compensate its members, officers, and appointees for their time. This Student Body Payroll shall issue from the General Fund, as described in Section 1 Part A, above. 2. The College Business Office shall distribute Student Body paychecks after making the </span></p>
                     <p class="c120 c151"><span class="c5">appropriate withholdings for Federal, State, and local taxes. 3. The Senate may vote to increase its salary upon achieving a two-thirds (2/3) vote of the </span></p>
                     <p class="c58"><span class="c5">entire Senate. If voted upon in the fall semester, the changes will not take effect until the inception of the next fall semester. If voted upon in the spring semester, the changes will not take effect until the inception of the next spring semester. 4. Before the Payroll Office&rsquo;s deadline each month, the Treasurer, the Vice Treasurer, or the Assistant Treasurer shall coordinate with the Payroll Office to pay wages accounted for by the Treasurer&rsquo;s Office, and for which the requisite funds exist in the organization&rsquo;s budget. The Treasurer, the Vice Treasurer, or the Assistant Treasurer shall also sign and coordinate with the Payroll Office for wages that shall be taken out of Senate&rsquo;s budget. The Treasurer, the Vice Treasurer, and the Assistant Treasurer shall be paid each month worked. The President and the Vice President shall be paid for five (5) months each semester. The Assistant Student Union Manager and the Pool Hall Managers shall be paid for four (4) months during each semester. The Judicial Board members and Senators shall be paid for four (4) months each semester. The Secretary shall be paid for four (4) months each semester. The Senate may also, by majority vote, decide to pay its officers during the summer. 5. The establishment of a new paid position or an increase in pay must be passed by a two- </span></p>
                     <p class="c45"><span class="c5">thirds vote of the entire Senate. </span></p>
                     <p class="c145"><span class="c2">E. Student Union Depreciation Fund </span></p>
                     <p class="c78"><span class="c5">As outlined in the Student Union Bylaws (Section 2, Part A), except in cases of extreme financial stringency &ndash; as determined by a two-thirds vote of the Senate &ndash; the Student Senate shall deposit one percent of all Student Body Fees in the Student Union Depreciation Fund. This fund shall consist of: </span></p>
                     <p class="c28"><span class="c5">1. the aforementioned one percent, 2. revenues generated by rental of the space 3. These monies shall be used for capital improvements to the Student Union and shall serve as </span></p>
                     <p class="c67"><span class="c5">the operating budget for cleaning and maintenance. 4. These monies shall be held within the Treasury and the Student Union Manager(s) shall have </span></p>
                     <p class="c85"><span class="c5">access to them via the disbursement procedures as described in Article II, Section 4, Part D. </span></p>
                     <p class="c57"><span class="c2">Section 2. Funding Procedures </span><span class="c5">The Vice President, Head Treasurer, Vice Treasurer and Assistant Treasurer shall be responsible for organizing and informing students and signators (as described in Article II, Section 5, Part A(i)) about the funding procedures outlined in the subsections of this section. </span></p>
                     <p class="c113"><span class="c2">A. Signator&rsquo;s Training </span></p>
                     <p class="c10"><span class="c5">1. Each semester, the Treasurer and Vice Treasurer shall arrange Signator&rsquo;s Training in </span></p>
                     <p class="c54"><span class="c5">consultation with the President, Vice President, the Director of Student Activities, and the Director of Community Safety. Signator&rsquo;s Training shall describe the Funding Procedure and Senate&rsquo;s expectations of signators as outlined in the Signator&rsquo;s Handbook. 2. Signator&rsquo;s Training shall be held no later than a week before Funding Poll descriptions are </span></p>
                     <p class="c77"><span class="c5">due. The Treasurer and Vice Treasurer shall be responsible for ensuring that the event is well publicized and the Vice President shall lead this training. </span></p>
                     <p class="c70"><span class="c2">B. Funding Poll </span></p>
                     <p class="c120 c156"><span class="c5">1. Each semester after the start of classes, the Vice President shall announce in the first </span><span class="c36">Quest </span></p>
                     <p class="c38"><span class="c5">and through other means of advertising that Senate is accepting submissions to the Funding Poll. Submissions to the Funding Poll shall be due the Friday before the week of the Funding Poll. The Funding Poll shall take place over three days during the week following the week of the Poll&rsquo;s announcement. The Funding Poll shall be administered by Senate using whatever method they choose fitting. The schedule and Funding Procedures for Funding Poll, Funding Circus, and Funding Hell shall be announced by the Vice President, Treasurer, and Vice Treasurer in this </span><span class="c36">Quest</span><span class="c5">, and Signator&rsquo;s Training, and through other means of advertising. 2. All organizations that submit a description of their purpose before the announced deadline and in the proper form shall be represented in the Funding Poll. The description published for the Funding Poll shall match the submitted description as closely as possible, but may be edited to make it more suitable for publication. The Treasurer and Vice Treasurer shall compile the descriptions and write the Funding Poll form in consultation with the Vice President, other members of Senate, and the Senate appointed Student Information Network (SIN) administrator(s). 3. The Funding Poll shall be used as a determination of the relative interest of the Student </span></p>
                     <p class="c108"><span class="c5">Body in the proposed organizations. 4. Each current student shall be allowed to vote an approval or disapproval of any of the </span></p>
                     <p class="c143"><span class="c5">submitted organizations. Each student may also abstain from voting on any number of organizations. An approval vote for an organization shall raise the vote total of that </span></p>
                     <p class="c120 c170"><span class="c5">organization by as much as two disapproval votes would lower the vote total of that organization. Each student shall also have the option of marking up to six approval votes as approval supervotes (Top Six) or or any combination thereof totaling no more than six supervotes. An approval supervote shall be counted as four (4) approval votes. 5. The results of the Funding Poll shall be tabulated and posted on SIN before the Funding </span></p>
                     <p class="c129"><span class="c5">Circus. </span></p>
                     <p class="c153"><span class="c2">C. Funding Circus </span></p>
                     <p class="c99"><span class="c5">1. Senate shall hear oral presentations from those organizations ranking forty and above in the fall semester or thirty and above in the spring semester Funding Poll if the signator of an applicable organization chooses to make a budget request. The Senate meeting at which these presentations are heard shall be known as the Funding Circus. The Funding Circus shall take place the Saturday following the Funding Poll. This request shall be written on a standardized form on the signator&rsquo;s web page as provided by the Student Senate and must be submitted to the Treasurer along with the itemized budget on the Friday before the Funding Circus. 2. Signators who are unable to attend the Circus may designate an organization member to </span></p>
                     <p class="c141"><span class="c5">present the organization&rsquo;s budget for the signator. The presentation of this member shall be taken as the presentation for the organization, and no signator may claim the allocation to their organization invalid because of their failure to appear at the Circus. </span></p>
                     <p class="c183"><span class="c2">D. Funding Hell </span></p>
                     <p class="c64"><span class="c5">1. The Sunday immediately following the Funding Circus, the Senate shall hold a meeting to allocate a portion of the General Fund to those organizations that have presented budget requests at the Funding Circus. The Funding Hell shall be considered to be an executive session meeting of the Senate. The decisions of the Funding Hell shall be understood as unofficial and will remain subject to change by consent of the Senate until they have been officially ratified at the next official meeting of Senate. Senate may choose to make these unofficial results available before their ratification; following official ratification, the results of Funding Hell shall be reported to the community and each signator shall be informed of their allotment. 2. The Student Body Vice President in prior consultation with the Treasurer and Vice Treasurer shall present to the Senate a budget outlining the expected payroll and administrative expenses the Senate will incur that semester. Included in this budget shall be the expected costs for Paideia (in the case of Fall semester), and the expected costs for the Griffin and the Handbook (in the case of Spring semester), regardless of whether a signator has been chosen for these organizations or not. Also included in the budget will be a payment of all outstanding debts from the previous semester (unless an extended payment period has been arranged by the Senate) and the allocation to the Finance Committee, as described in Article II, Section 2, Part F(iii). 3. The Treasurer and Vice Treasurer shall also include in the report a summary of each </span></p>
                     <p class="c14"><span class="c5">organization&rsquo;s financial record from the last semester. This summary shall consist of: (a) what percentage of the money allocated to each organization has been backed by receipts turned in by that organization&rsquo;s signator; (b) what percentage of the money allocated to each organization was actually spent. The report shall concern only the finances of Funding Hell, Funding Circus, and Identity-Based Funding. This report shall be taken into consideration in </span></p>
                     <p class="c100"><span class="c5">Senate&rsquo;s decisions on allocations. The Vice President shall distribute copies of this report to all the members of Senate present. </span></p>
                     <p class="c30"><span class="c2">E. Identity-Based Funding </span></p>
                     <p class="c120 c134"><span class="c3">1. </span><span class="c5">The Student Body Senate&rsquo;s Mission Statement for this funding pool is as follows: &ldquo;The </span></p>
                     <p class="c62"><span class="c5">Student Senate of the Autonomous Student Body of Reed College recognizes that students may face institutional barriers at Reed or in America that prevent equal access to services, aid, and opportunities on the basis of identity. The purpose of this funding pool is to finance the work of student groups that support communities that are historically marginalized at Reed or in the nation at large. These include communities that share a racial, ethnic, cultural, religious, or other historically marginalized identity. In recognizing this, we hope to guarantee a financial baseline for student organizations that aims to offer support for these disadvantaged students as a means of building community and providing resources that are otherwise insufficient or absent at Reed.&rdquo; </span><span class="c3">2. </span><span class="c5">During the first two weeks of each semester the Student Senate will advertise Identity-Based Funding as an opportunity for relevant student groups. Interested groups shall submit a mission statement. A committee comprised of Senate, the Vice President, the President, the Treasury, and at least two or up to three non-Senate students who are either MRC interns or appointed students shall collectively review these proposals. </span><span class="c3">3. </span><span class="c5">The committee will determine if a group&rsquo;s mission statement is in accordance with the </span></p>
                     <p class="c62"><span class="c5">Identity-Based Mission Statement by a consensus minus one vote. If a group&rsquo;s mission statement is found not to be in accordance with the Identity-Based Funding Mission Statement, as determined by a consensus minus one, the group will be given both the committee&rsquo;s reasoning behind the decision and the opportunity to appeal the decision. If the group appeals their decision they must submit a letter addressing the committee&rsquo;s concerns and an adjusted mission statement, if relevant. The committee will determine based on the appeal, with a consensus minus one vote, whether to include the group. Groups determined not to fall within the mission of the Identity-Based Funding Mission Statement must be informed of the final decision with ample opportunity to re-submit their budget proposals in Funding Poll. </span><span class="c3">4. </span><span class="c5">After determining which groups&rsquo; mission statements are in accordance with the Identity- </span></p>
                     <p class="c120 c123"><span class="c5">Based Funding Mission Statement the committee will assess the final list of budgets and allocate the available funds. The goal of this funding pool is to ensure every group eligible for this program receives adequate funds to meet their baseline needs. Thus, resources that directly benefit students or that are necessary for the group to operate will be prioritized over requests for more supplementary funding. 5. The Student Body Treasury shall recommend an allocation of no less than $10,000 to this </span></p>
                     <p class="c159"><span class="c5">funding pool each semester. </span></p>
                     <p class="c197"><span class="c2">F. Finance Committee </span></p>
                     <p class="c120 c186"><span class="c5">1. There shall be a standing committee of the Senate under the name of the Finance </span></p>
                     <p class="c120 c137"><span class="c5">Committee. This committee shall hear all petitions for: additional funds to be allocated after the Funding Hell; amendments to the allocations made at the Funding Hell; and allocations to organizations not represented on the Funding Poll. 2. The Finance Committee shall consist of the Vice President of the Student Body, a minimum of two other Senators and a maximum of three, the Student Body Treasurer, the Student Body Vice Treasurer, and the Student Body Assistant Treasurer. The Vice President shall be </span></p>
                     <p class="c120 c127"><span class="c5">the chairperson. The presence of two-thirds of the total number of members shall constitute quorum. The Treasurers shall be considered voting members. The Treasurers shall make comments on the submitted budgets and shall be responsible for ensuring that: (a) after receiving the approval of Senate, the funds for category transfers and allocations are moved from Finance Committee to Finance Committee Holding on the treasury computer; (b) the approved budgets and comments are available to the student body on the Finance Committee webpage on SIN; (c) the approved budgets and comments are digitally archived on the Treasurer&rsquo;s computer at the end of each semester. The committee shall meet once a week while school is in session and funds are available. Its meeting place and time shall be posted each semester on SIN and announced through the SB-Info email list at the beginning of each semester. 3. At the Funding Hell for each semester, the Senate shall allocate to the Finance Committee such funds as it deems necessary for its operation as described in Article II, Section 2, Part D(ii). Should this amount be insufficient, the Senate may allocate more funds to the committee as necessary. 4. The Finance Committee may, by a majority vote of its members, recommend to the Senate </span></p>
                     <p class="c81"><span class="c5">that funds be allocated to any Student Body organization from the Committee&rsquo;s budget as allocated in Article II, Section 2, Part D(ii). The committee may not make decisions to allocate independent of Senate approval. 5. The following categories shall be used for the holding of Student Organization&rsquo;s funds, as described in the Signator&rsquo;s Handbook: Wages, Administration, Refreshments, Capital Improvements, Entertainment, Miscellaneous, Revenue, and Frozen. 6. The committee shall also hear requests for additional funds. If any one member of the </span></p>
                     <p class="c28"><span class="c5">Finance Committee feels such a decision is inappropriate, it shall be referred to the full Senate for discussion. All recommendations for additional funds must be approved by the Senate. Submitted income in excess of expected revenue may be re-allocated to other categories (except wages) for expenditure, and shall not be considered an increase in the total allocation to the organization. Budget amendments which are requests to transfer funds from one category to another shall be called category transfers. 7. Budget amendments that are requests to transfer funds from the signator&rsquo;s organization to </span></p>
                     <p class="c12"><span class="c5">another organization, for purposes entirely unrelated to those of the donor organization, shall be called gift transfers. These transfers are approved by agreement of the Treasurer and Vice President and reported to the Senate. 8. At times when school is in session but when Finance Committee will not be meeting before the category transfer is needed by the organization (as in the case of many presentations and other social events), the signator of the organization may submit the category transfer request to the Treasurer or the Vice Treasurer. The Treasurer, the Vice Treasurer, or the Assistant Treasurer shall then follow the same procedure as for similar situations during Winter and Summer Break as outlined above in Article II, Section 2, Part E(vii). Finance Committee and Senate shall then determine the validity of such approvals in the same manner as outlined above in Article II, Section 2, Part E(vii). </span></p>
                     <p class="c157"><span class="c2">Section 3. The Vice President </span><span class="c5">The Vice President shall be the signator for the Senate. They must therefore sign a signator&#39;s contract accepting responsibility for all funds that Senate allocates to itself. The Treasurers and Vice President shall meet once every week for at least half an hour to go over Senate&#39;s budget and </span></p>
                     <p class="c43"><span class="c5">finances and to prepare for the next week&#39;s Finance Committee meeting and Senate meeting and any other relevant upcoming events. </span></p>
                     <p class="c9"><span class="c2">Section 4. Treasurer&#39;s Office </span></p>
                     <p class="c190"><span class="c2">A. Appointments and Duties </span><span class="c5">At the end of each semester, the Senate shall appoint an Assistant Treasurer for a three-semester tenure as an officer in the Student Body Treasurer&#39;s office to begin at the start of the following semester. During the first semester of this tenure the individual will be Student Body Assistant Treasurer, during the second semester they will become Student Body Vice Treasurer, and during the third semester they will become Student Body Treasurer. Senate shall delegate the responsibility of administering the disbursement of Student Body Funds to the Student Body Treasurer, the Student Body Vice Treasurer, and the Student Body Assistant Treasurer. The Assistant Treasurer and Vice Treasurer will be understood as a Treasurers-in-training and are subject to the approval of Senate in the described manner. </span></p>
                     <p class="c39"><span class="c5">1. The main duties of the Assistant Treasurer (other than generally helping the Treasurer and Vice Treasurer) shall be to help handle the accounting for Wages and Revenue and to help do Bank Reconciliations. The Assistant Treasurer shall also write checks and do all the accounting that comes therewith. 2. The Vice Treasurer shall be responsible for doing the Bank Reconciliations and for handling the accounting for the Wages and Revenue. The Vice Treasurer shall also help the Treasurer prepare the monthly financial report to Senate, and shall keep a record of the transactions approved at Finance Committee every week for the Treasurer&rsquo;s office accounting. 3. Upon request the Vice Treasurer shall notify each signator in writing or via the student body </span></p>
                     <p class="c120 c174"><span class="c5">web server of the amount of money remaining in their organization&rsquo;s budget. 4. The Treasurer, the Vice Treasurer, and the Assistant Treasurer must each hold office hours </span></p>
                     <p class="c120 c187"><span class="c5">when they can be reached by signators and must notify all signators of these hours. 5. Each semester, the appointed Treasurer, Vice Treasurer, and Assistant Treasurer shall sign a </span></p>
                     <p class="c94"><span class="c5">contract in which they shall each: agree to perform their duties as outlined in these bylaws; acknowledge their agreed upon compensation; and, accept all legal fees incurred as a result of any litigation the Senate may decide to commence due to any unauthorized actions they may perform while in office. 6. The Student Body President and Vice President shall also sign similar contracts relating to </span></p>
                     <p class="c41"><span class="c5">any financial duties to which they are bound by these bylaws. 7. The President shall keep and file the original contract which the Treasurer signs; a copy shall </span></p>
                     <p class="c92"><span class="c5">be given to the Director of Student Activities. The Treasurer shall keep and file the original contracts signed by the President, Vice President, Vice Treasurer, and Assistant Treasurer; a copy shall be given to the Director of Student Activities. The Treasurer shall be responsible for writing all such contracts and must have them approved by the Senate before the signee signs them. 8. In situations of need, the Senate may also hire a former member of the Treasury as a </span></p>
                     <p class="c107"><span class="c5">financial consultant. The Consultant may be hired to help with the audit, train new treasurers, prepare for Funding Hell, or provide other services that the Senate requires in an emergency situation. A consultant cannot be paid more than the head treasurer. A sitting Senator may become a consultant if they have prior experience within the treasury. A sitting Senator who is hired as a consultant cannot be paid more than half of the head treasurer&rsquo;s pay in addition to their Senate compensation. </span></p>
                     <p class="c20"><span class="c5">9. Should a Treasurer resign in the middle of a term, a new Assistant Treasurer shall be </span></p>
                     <p class="c93"><span class="c5">appointed as soon as possible. The Vice Treasurer shall be promoted to Treasurer, and the previous Assistant Treasurer shall assume the office of Vice Treasurer. 10. Should a Treasurer resign following their appointment but before the beginning of the next </span></p>
                     <p class="c119"><span class="c5">semester&rsquo;s term, the empty position shall be filled as stipulated in Article II, Section 4, Part A(ix). The Senate shall have the option to appoint one of the candidates originally interviewed for the Assistant Treasurer position or reopen the appointments process. </span></p>
                     <p class="c161"><span class="c2">B. Use of the Treasurer&rsquo;s Office </span><span class="c5">The Treasurer, the Vice Treasurer, the Assistant Treasurer, the Vice President, and the consultant(s) shall all have keys to the Treasurer&rsquo;s office. Each shall be given their key for the length of their office. No other student shall have a key to the office unless they are under hire by the Senate for services related to the Office. Such a student must sign a contract which delineates all the agreed upon conditions of their compensation and in which they acknowledge that they have read this part of this section of this article of these bylaws. The Treasurer shall be responsible for writing such contracts and shall have them approved by the Senate before the student signs it. </span></p>
                     <p class="c162"><span class="c2">C. Termination </span><span class="c5">The Senate may terminate the term of the Treasurer, Vice Treasurer, Assistant Treasurer, or Consultant by a two-thirds vote of the full Senate for </span><span class="c36">any </span><span class="c5">reason, including, but not limited to, failure to comply with these bylaws or financial irresponsibility. Upon such a termination, a new Assistant Treasurer shall be appointed according to Article II, Section 4, Part A(x) above. </span></p>
                     <p class="c176"><span class="c2">D. Disbursement of Funds </span></p>
                     <p class="c111"><span class="c5">1. The Treasurer, the Vice Treasurer, and the Assistant Treasurer shall be personally </span></p>
                     <p class="c58"><span class="c5">responsible for receiving and processing all requests for disbursement of allocated funds from registered signators of organizations The Treasurer, the Vice Treasurer, or the Assistant Treasurer shall promptly disburse funds to the signator if and only if the signator has completed a written acceptance of financial responsibility, demonstrated financial responsibility, completely and properly filed their request for disbursement, and if said request does not exceed the limits of spending set by the Senate by that organization. If the signator does not qualify under the above conditions, no disbursements will be made at the request of that signator. The Treasurer, the Vice Treasurer, the Assistant Treasurer, and the Vice President also shall not disburse, in any category, funds above those the Senate has approved. If the Treasurer, the Vice Treasurer, the Assistant Treasurer, or the Vice President does so as the result of an accounting error, they must report it at the next Senate meeting; Senate must then decide whether to approve it or to make the responsible party (be it the Treasurer, the Vice Treasurer, the Assistant Treasurer, or the President) pay for it themself. 2. If the Treasurer, the Vice Treasurer, or the Assistant Treasurer receives a request for </span></p>
                     <p class="c184"><span class="c5">disbursement of funds for an item or service that they are not sure meets the requirements for the category under which the money is being requested; or if the Treasurer, the Vice Treasurer, or Assistant Treasurer receives a request for disbursement of funds for an item or service that they are not sure the Senate would approve for Student Body ownership because of liability concerns; or if, for any other reason, the Treasurer, the Vice Treasurer, or Assistant Treasurer question the status of the request, then the Treasurer, the Vice Treasurer, or Assistant Treasurer shall refer all such questionable disbursements to the Vice President for approval (or the President if the Vice President is unavailable). If, for any </span></p>
                     <p class="c98"><span class="c5">reason, the Treasurer, the Vice Treasurer, or Assistant Treasurer is forced to make a decision on their own on a disbursement that they deemed questionable, then they shall report it to the next meeting of the Senate. 3. As specified by the procedures outlined in the Signator&rsquo;s Handbook, the Treasurers may </span></p>
                     <p class="c41"><span class="c5">make available to signators checks written for a specific amount to a particular vendor for the cost of an item pre-approved in the budgeting process or through Finance Committee, known hereafter as a &ldquo;loan.&rdquo; All loans are subject to the approval of the Treasurers; if a loan is granted, a receipt for the specific item and amount must be returned to the Treasurers within a period of two weeks. If after two weeks no receipt verifying the purchase has been submitted, the signator of the organization will be considered in default of payment, and subject to having their business account billed for the amount of the loan, their position suspended, or both. This information shall be published in the Signator&rsquo;s Handbook in accordance with the procedure prescribed herein. 4. All checks shall be signed by the Treasurer, the Vice Treasurer, the Assistant Treasurer, the Vice President, or a currently sitting consultant. </span><span class="c36">No check shall ever be made out to &ldquo;cash&rdquo; without the prior written permission of the Vice President. </span><span class="c5">Each check shall list the organization for which it is written, and the expenditure category from which it is taken. 5. The Student Body Treasurers shall communicate at least monthly with the Student Activities </span></p>
                     <p class="c120 c155"><span class="c5">Office regarding the transfer of funds between the two offices. 6. The Treasurer, the Vice Treasurer, or the Assistant Treasurer shall not disburse funds </span></p>
                     <p class="c54"><span class="c5">beyond those in possession of the Student Body; an amount defined by the current, correctly updated, checkbook balance. 7. Checks written to either the Vice President, the Treasurer, the Vice Treasurer, or the </span></p>
                     <p class="c55"><span class="c5">Assistant Treasurer must be approved by a vote of the Senate; at no time shall a check be signed by its payee. The President shall only write checks in emergency situations. 8. In cases where a disbursement is being made directly to Reed College in payment for College </span></p>
                     <p class="c21"><span class="c5">services provided to more than one organization, the Treasurer or Vice Treasurer shall record such payment, detailing the amount of the total check that shall be charged to each organization, and the amount per organization charged to each expenditure category. In this case only, such a record shall serve as a receipt of payment. 9. The last day the Treasurer, the Vice Treasurer, or the Assistant Treasurer shall accept </span></p>
                     <p class="c104"><span class="c5">disbursement requests (except in emergency situations and for organizations that operate in between semesters) shall be determined by the Treasurer and the Vice President and reported to the signators at least three (3) weeks in advance. The last day the Treasurer, the Vice Treasurer, the Assistant Treasurer, or the Vice President may write checks for money that has been allocated for a particular semester is on the day before the next semester begins (unless other arrangements have been made with the Senate). 10. Funds for organizations (and miscellaneous activities that Senate funds) that do not go through the Funding Poll shall be considered &quot;floating funds.&quot; &quot;Floating funds shall be categorized under &quot;Miscellaneous&quot; as part of Senate&#39;s budget (unless a person signs a signator&#39;s contract for the funds and Senate authorizes an </span><span class="c36">internal transfer </span><span class="c5">of the funds to the new organization). </span></p>
                     <p class="c75"><span class="c2">E. Acceptance of Funds </span><span class="c5">i. The Treasurer, the Vice Treasurer, or the Assistant Treasurer shall keep digital and hard copies of the received and deposited checks in the Treasurers&rsquo; Office. </span></p>
                     <p class="c110"><span class="c5">ii. The safe in the office shall be used for emergency situations in which the Treasurer, the Vice Treasurer, or Assistant Treasurer must accept cash for revenue. The Treasurer, the Vice Treasurer, the Assistant Treasurer, and the Vice President shall each have access to the safe for the length of their office; at the end of their respective tenures, they shall relinquish their access to the next holders of their respective offices. </span></p>
                     <p class="c82"><span class="c2">F. Accounting </span></p>
                     <p class="c37"><span class="c5">1. The Treasurer, the Vice Treasurer, and the Assistant Treasurer must attend the entirety of </span></p>
                     <p class="c120 c191"><span class="c5">each Senate meeting, to inform and advise the Senate of the financial state of the Student Body. 2. At the third regularly scheduled Senate meeting of each month the Treasurer and Vice </span></p>
                     <p class="c120 c132"><span class="c5">Treasurer shall provide a report to </span><span class="c36">each member </span><span class="c5">of the Senate and the Director of Student Activities, this report will be the relevant monthly reconciliation documents. The report shall contain a sum of all of the values of all of the checks issued that month; and the account balances for the checking, market interest savings, and Student Union Depreciation fund (as defined by the Student Union Bylaws). This report shall be submitted to the Vice President before the meeting for approval, and shall be appended to the minutes of that meeting. 3. Each month the Vice Treasurer will prepare a bank reconciliation each month. This </span></p>
                     <p class="c67"><span class="c5">reconciliation shall be used to verify or correct the current checkbook balance. A report of the reconciliation, </span><span class="c36">including any discrepancy between the bank balance and the ledger balance and any corrections made to the ledger, </span><span class="c5">shall be included in the Treasurer&rsquo;s monthly report to the Senate as described in Article II, Section 4, Part F(ii). All reconciliations shall be filed together with the corresponding bank statements and cancelled checks, and shall be kept for a period of seven years. If the Vice Treasurer is unable to complete the bank reconciliation on any particular month, it shall be completed by the Treasurer or Assistant Treasurer. 4. Each check written shall be accompanied by a receipt as a proof of payment. Each receipt shall be marked with the check number of the check it accompanies. A receipt shall be defined as a written acknowledgement that a specified sum of money has been received in exchange for services and/or merchandise or goods. The receipt must be given by the provider of the services and/or merchandise or goods. The validity of the receipt is left to the discretion of the Treasurer. Receipts for advances made to signators must be given to the Treasurer, the Vice Treasurer, or Assistant Treasurer within two (2) weeks of the check&rsquo;s date. It is the responsibility of the Treasurer or the Vice Treasurer to send signators that have not turned in receipts at least three notes before the Funding Hell of the next semester (unless the signator turns in the receipts before then) reminding them of the consequences of not turning in receipts, and at least three notes before the Fall audit (unless the signator turns in the receipts before then) reminding them of the imperative of gathering receipts for the upcoming audit. 5. In cases where a signator has not produced receipts in a quantity sufficient to demonstrate </span></p>
                     <p class="c130"><span class="c5">financial responsibility, or has otherwise demonstrated financial irresponsibility, the Treasurer may request that the Vice President suspend the position of that signator. If the Vice President approves, the signator shall be notified by the Treasurer of their suspension, and shall remain suspended until the next Senate meeting. At that meeting, the full Senate shall vote as to the competence of the signator, after hearing a statement by the Treasurer, and, if desired by the signator, a statement by the signator as well. The signator may be removed from office by a majority vote of the Senate. If the signator is removed the Treasurer will see that the vacancy is advertised, and the Senate shall appoint a new signator </span></p>
                     <p class="c78 c120"><span class="c5">for that organization. If the Senate does not vote to remove the signator, that signator shall be reinstated. The Senate may also vote to remove a signator that has not been suspended, and the President may suspend a signator without a recommendation of the Treasurer. The signator may also be charged for any portion of those disbursements for which s/he has not produced a valid receipt by having their Business Office account billed. 6. All payroll shall be paid through the services of the Business Office of Reed College. The </span></p>
                     <p class="c103"><span class="c5">Treasurer, the Vice Treasurer, or Assistant Treasurer shall coordinate with the Business office to issue student paychecks. In cases of financial need, the Treasurer or Vice Treasurer may advance to a student who is paid regularly by the Student Body a quantity of funds not to exceed those funds the student is expected to earn during the month. The Treasurer or Vice Treasurer must submit a record of Senate&rsquo;s approval for this advance to the Business Office within three working days, and the advance must be deducted from the next paycheck of the student. The Treasurer shall not make advances without the approval of the superior of the student; nor when the Student Body does not have or does not appear to have the funds to support such an advance. The total amount of advances in any given month may not exceed $3000.00. 7. The Student Body need not accept responsibility for those charges made in the name of the </span></p>
                     <p class="c120 c195"><span class="c5">Student Body without approval, whether such charges were made by signators or by other students. 8. All records of a financial nature shall be kept for a period of seven years. 9. Both a hardcopy and a computer file shall be kept on every organization, including the Senate. All important financial transactions must be documented in hardcopy. The Treasurer, the Vice Treasurer, and Assistant Treasurer must update these files every week by recording all changes in all organizations&rsquo; finances in each. 10. Every summer, the Treasurer shall prepare the financial records from the Fall and Spring semesters for the upcoming audit according to established guidelines and in consultation with the assigned auditor. </span></p>
                     <p class="c19"><span class="c2">G. Signators </span></p>
                     <p class="c47"><span class="c5">1. The Treasurer, the Vice Treasurer, and Assistant Treasurer shall provide to signators on </span></p>
                     <p class="c46"><span class="c5">request information regarding the remaining funds in each expenditure category for their organizations. 2. Before the date of signators&rsquo; training, the </span><span class="c36">Signator&rsquo;s Handbook </span><span class="c5">should be revised and printed </span></p>
                     <p class="c116"><span class="c5">in coordination with the Director of Student Activities. The Vice President and Treasurer shall review the </span><span class="c36">Signator&rsquo;s Handbook </span><span class="c5">each summer, make changes as necessary, and make it available to the Reed Community. The </span><span class="c36">Handbook </span><span class="c5">shall describe the practical expectations of signators. 3. Neither the Treasurer nor the Vice Treasurer, nor the Assistant Treasurer nor the President </span></p>
                     <p class="c146"><span class="c5">nor the Vice President shall be: a) the signator for any organization; or, b) an officer (defined as a member involved in the finances of the organization) in any organization other than the Senate. </span></p>
                     <p class="c68"><span class="c2">Section 5. Organization Finances </span></p>
                     <p class="c177"><span class="c2">A. Signators </span></p>
                     <p class="c120 c150"><span class="c5">1. The signator of an organization shall be defined as that member who accepts financial </span></p>
                     <p class="c23"><span class="c5">responsibility for an organization or an event. Student body organizations may have more </span></p>
                     <p class="c17"><span class="c5">than one signator. Signators must be currently enrolled and matriculating members of the Student Body. The signator shall be responsible for submitting a budget request to the Senate, approving and accepting responsibility for all disbursements made for the organization, and managing the finances of the organization. The signator of each organization must sign a statement of financial responsibility each semester that s/he holds the position of signator. In those cases where Senate has allocated organizational space, the signator shall ensure that the space meets all applicable codes and policies of Reed College and the City of Portland. Any fines incurred due to code violations shall be the sole responsibility of the signator. 2. At the beginning of each semester the Senate shall approve the list of signators as presented </span></p>
                     <p class="c139 c120"><span class="c5">by the Treasurer and Vice Treasurer. This list shall be entered in the minutes of the Senate, and amendments to it shall also be entered in the minutes. 3. Students who act as signators and submit disbursement requests as signators but have not </span></p>
                     <p class="c41"><span class="c5">been approved by Senate or have not completed a statement of financial responsibility shall be held personally responsible for all disbursements made under their signature and all debts that they incur. Hence, if any student in any organization submits a disbursement request and receives funds for which the official signator refuses to sign, then the Treasurer, the Vice Treasurer, or Assistant Treasurer must charge said student&rsquo;s Business Office account for the amount that the organization was not authorized to spend. 4. The Treasurer, the Vice Treasurer, and the Assistant Treasurer may charge the Business </span></p>
                     <p class="c120 c178"><span class="c5">Office account of a signator with an amount to be specified by the Senate if the signator overspends the expenditure category limits of their organization or misappropriates student body funds. Such a charge must be approved by the Senate and must not exceed the amount by which the signator overspent or misappropriated, except to cover bank or legal fees incurred by the overspending. A signator&rsquo;s Business Office account may also be charged if they provide inadequate documentation of their expenditures. 5. Signators for organizations for which it is difficult to retrieve all the revenue checks before the end of the semester (such as </span><span class="c36">The Quest </span><span class="c5">and the </span><span class="c36">Student Body Handbook</span><span class="c5">) are exempt from incurring fines for late repayment from the Senate, provided that they make arrangements with the Treasurer or Vice Treasurer to have all the revenue in before the end of the next semester. 6. A signator may be suspended and/or removed from office if s/he acts in an irresponsible </span></p>
                     <p class="c25"><span class="c5">manner, especially but not exclusively in regards to the financial matters of theirorganization. Such an action would follow the course described in Article II, Section 4, Part F(v). Any signator removed from office may not be a signator for the period of one year, unless otherwise specified by the Senate. 7. Senators who are Signators shall not be present for the discussion of funding decisions for </span></p>
                     <p class="c69"><span class="c5">their organization(s). Senators may present budgets but are not permitted to participate in the decision-making process. Senators may not vote to allocate money to organizations they signate. </span></p>
                     <p class="c97"><span class="c2">B. Accounting </span></p>
                     <p class="c42"><span class="c5">1. All revenue of an organization must be surrendered to the Treasurer or Vice Treasurer </span></p>
                     <p class="c71"><span class="c5">within fifteen business days of its receipt. Once expected revenue has been met, the Finance Committee may allocate excess revenue into expenditure categories if the signator so requests. The Treasurer, Vice Treasurer, or Assistant Treasurer shall produce a receipt for </span></p>
                     <p class="c120 c188"><span class="c5">the signator, detailing the amount received and the date on which it was received, for each deposit of revenue to the Treasurer or Vice Treasurer. 2. Stop payments will be issued on all checks declared &lsquo;lost&rsquo; by the signator, and a charge shall </span></p>
                     <p class="c101"><span class="c5">be made against the organization for replacement of such checks equal to the cost of the stop payment. 3. The responsibility for producing receipts for all disbursements for an organization shall rest </span></p>
                     <p class="c95"><span class="c5">in the hands of the signator, </span><span class="c36">no matter to whom the check is written</span><span class="c5">. 4. All wages shall be paid through the Business Office. Fees for performers and public speakers </span></p>
                     <p class="c120 c158"><span class="c5">shall not be considered wages. 5. All expenditures must be appropriate to the objectives and budget of the organization, as </span></p>
                     <p class="c79"><span class="c5">approved by the Senate. 6. All excess revenue from one </span><span class="c36">Quest </span><span class="c5">Board&rsquo;s advertisements must be transferred to the next </span></p>
                     <p class="c74"><span class="c5">semester&rsquo;s Board under the category of Capital Improvements for the continual upgrading of the computers in the Student Publications Office. </span></p>
                     <p class="c135"><span class="c2">C. Independence </span></p>
                     <p class="c120 c180"><span class="c5">1. An organization shall be defined as any group with a signator that submits a budget request to the Senate. Any group that does not request an allocation of funds from the Senate shall be independent from the Student Body. Groups that request loans from the Student Body may still be considered independent groups, so long as payment on these loans is reasonably assured. 2. An independent group may not use the name, facilities, property, or resources of the Student Body or of Reed College in such a manner as to earn a profit. Nor shall any independent group make any charge to any account of the Student Body, whether maintained by the Treasurer&#39;s office or the Business Office. 3. No independent group shall be the financial responsibility of the Student Body in any way. 4. No independent group shall use the name of Reed College or the Reed Institute or the Reed </span></p>
                     <p class="c148 c120"><span class="c5">College Student Body without the explicit written permission of each entity. 5. Senate funds student publications for the distribution of content within, to, and for the Reed Community. Senate-funded publication beyond this community shall be contingent on a meeting between the editors of the publication and a senate representative, as well as a majority approval of Senate each semester. All publications must allow content creators to opt-out of general distribution. </span></p>
                     <p class="c121"><span class="c2">Section 6. Oversight and Review </span></p>
                     <p class="c63"><span class="c5">1. The Student Body Finances shall undergo a professional audit yearly. This audit shall occur during the Fall semester. The Treasurer must give a detailed report to the Senate of the results of this audit the week after the auditors have reviewed the Treasurer&rsquo;s office records. 2. It shall be the responsibility of the Treasury to ensure that inventories of substantial items </span></p>
                     <p class="c76"><span class="c5">are updated and maintained for any organizations requesting funding from the student body. Furthermore, the Treasury shall be responsible for conducting internal audits of student body organizations, sampling 10 transactions from a range of student organizations. These internal audits must be conducted a minimum of once a semester. An audit shall review the maintenance of practices outline in the Treasurer&rsquo;s Handbook including adequate documentation of purchases, correctly filled out forms, and proper accounting. The results of these audits may be used in making future funding decisions, but failure of an audit does not preclude further funding. </span></p>
                     <p class="c4"><span class="c5">3. The Student Body President and Vice President shall have access to all financial records of </span></p>
                     <p class="c16"><span class="c5">the Student Body. Furthermore, it is the duty of the Student Body President and Vice President (and of all the members of Senate in general) to oversee the actions of the Treasurer, Vice Treasurer and Assistant Treasurer and to ensure that the Treasurer, Vice Treasurer and Assistant Treasurer are fulfilling their responsibilities as put forth in these Bylaws. 4. During the academic year, the Vice President, Treasurer, and Vice Treasurer shall meet at least once every two weeks with the Director of Student Activities to discuss matters pertaining to Student Body Finances. 5. The Treasurer or Vice Treasurer shall, upon request of the Director of Student Activities, </span></p>
                     <p class="c31"><span class="c5">provide any financial records of the Student Body. 6. The Director of Student Activities shall have no signatory authority for any Student Senate </span></p>
                     <p class="c112"><span class="c5">funded organization. </span></p>
                     <p class="c8"><a name="sin-bylaws-article3">
                     <h2 class="rainbow-article-3">Article III. Senate and Student Body Committees, Boards, and Managers </h2>
                     </p>
                     <p class="c131"><span class="c2">Section 1. Senate Committees </span></p>
                     <p class="c125"><span class="c2">A. Appointments Committee </span></p>
                     <p class="c56"><span class="c5">1. The Senate Appointments Committee shall interview candidates for all positions appointed </span></p>
                     <p class="c151 c120"><span class="c5">by the Senate, and present to the Senate recommendations for appointments to those positions. 2. Short descriptions of all available positions shall be published in Student Body Info and </span></p>
                     <p class="c62"><span class="c5">social media the week prior to the corresponding interviews. Available positions shall also be announced at public senate meetings in the same period, when possible. Appointments may be publicized elsewhere at the Committee&rsquo;s discretion. 3. </span><span class="c32">4. The Committee shall be composed of five senators, including the Chair. </span><span class="c5">5. The presence of three Senators and the Chair shall constitute quorum for meeting of the </span></p>
                     <p class="c120 c139"><span class="c5">Appointments Committee. 6. In order to recommend an appointment to the Senate, the Appointments Committee must </span></p>
                     <p class="c120 c138"><span class="c5">vote to approve the recommendation by a minimum standard of one less than consensus. If there is more than one dissenting vote for a particular recommendation, applications for the position shall be re-opened for another week. 7. Before its final meeting in each Senate term, the Appointments Committee shall review the status of all paid positions to which students have been appointed. It is up to the discretion of the Appointments Committee Chair to review other positions to which students are appointed. 8. In instances where an appointed student has failed to perform the full duties of their role, the Appointments Committee may recommend the removal of that student from their appointment. To recommend an appointee&rsquo;s removal, the Committee must vote by a minimum standard of one less than consensus. The Committee may only vote after making a reasonable effort to ascertain the appointee&rsquo;s track record in their position, whether by consulting with the appointee or their supervisor. Because the Appointments Committee oversees the appointments of many different types of positions, specific guidelines pertaining to individual positions are to be recorded in the Appointments Committee Chair Handbook. </span></p>
                     <p class="c11"><span class="c5">9. In instances where an elected student position is paid through student body funds, the </span></p>
                     <p class="c65"><span class="c5">Appointments Committee may still recommend the removal of that student from their role. The Committee&rsquo;s minimum voting standard of one less than consensus applies to this recommendation. 10. All recommendations for removal from an appointed position require a two-thirds majority </span></p>
                     <p class="c0"><span class="c5">vote from the whole Senate. In the cases where the Senate has recommended the appointment of the student to the President of the college, this vote shall constitute a retraction of that recommendation. 11. Following removal from an appointment, the Senate will announce that the position in </span></p>
                     <p class="c120 c148"><span class="c5">question is now open during their next public meeting. 12. Guests to the Appointments Committee shall be understood as advisers to the Committee, providing knowledge of the position based on their previous experience and familiarity. All advisers shall participate in the interviews and in an initial deliberation of the applicants. After initial deliberations, the advisers shall choose one of their group to contribute towards the final deliberation for the position. That single representative shall be considered a voting member in the determination of consensus minus one. Only the Senate members of the Appointments Committee and the selected adviser shall participate in the vote for the final recommendation to Senate. 13. The deliberations of the Appointments Committee are confidential to the participating members of the Committee and the rest of Senate. All guests to the Appointments Committee shall be held to the same standards of professionalism and confidentiality as the Senators on the Committee. 14. If a Senator on the Appointments Committee applies for an appointed position, that senator shall not participate as a member of the Committee for the duration of the appointment process for that position. 15. Decisions made by the Appointments Committee shall be based on a candidate&#39;s knowledge, </span></p>
                     <p class="c80"><span class="c5">skills, and abilities relevant to those required for the duties of the position. In order to judge these qualities in candidates, Appointments Committee may only consider information defined as admissible: the standard of admissibility of such information is to be maintained in the Appointments Committee Handbook. These decisions shall be free from patronage and from discrimination against protected classes (see Reed&rsquo;s Discriminatory Harassment and Sexual Misconduct Policy for a complete list of protected classes). 16. The Appointments Committee Chair shall be responsible for advertising all open positions, accepting applications and scheduling interviews. The Chair shall be responsible for leading the interview process, and briefing all participants on the nature of the position being filled, the standard of admissible information, and the deliberative process.The Chair shall also be responsible for keeping a record of all students appointed, all positions Appointments Committee is responsible for, the duration of the terms of those positions, and at what time of year each appointment must be conducted. This record shall be passed down to the next Chair. 17. The Appointments Committee Chair shall be selected by the current semester&rsquo;s Senate for </span></p>
                     <p class="c83"><span class="c5">the following term by secret-ballot majority vote. Candidates shall be all members of the incoming Senate. The vote shall occur after elections results have been confirmed but before the end of the term, at a meeting of the Senate at which members from both the current and following semester terms are present. Should the Chair position become vacant between semesters, the Student Body President may appoint an interim Chair until the next semester&rsquo;s Senate can meet to select a new Chair from among its members. </span></p>
                     <p class="c147"><span class="c2">B. Finance Committee </span></p>
                     <p class="c120 c167"><span class="c5">1. Finance Committee shall have the responsibilities outlined above in Article II, Section 2, </span></p>
                     <p class="c89"><span class="c5">Part E. </span></p>
                     <p class="c136"><span class="c2">C. Establishment of Other Committees </span></p>
                     <p class="c114"><span class="c5">1. Other standing committees may be established as needed by a majority vote of the Senate. </span></p>
                     <p class="c15"><span class="c5">These additional committees may also be dissolved by a majority vote of the Senate. </span></p>
                     <p class="c87"><span class="c2">Section 2. Student Committees and Boards </span></p>
                     <p class="c1"><span class="c2">A. Composition of Student Committees and Boards </span></p>
                     <p class="c120 c175"><span class="c5">1. All student vacancies and means of appointment shall be publicized. 2. Appointees to the following positions shall be ratified by a two-thirds vote of the entire </span></p>
                     <p class="c89"><span class="c5">Senate: </span></p>
                     <p class="c193"><span class="c5">a. All student Judicial Board members b. Student Body Treasurers c. Renn Fayre Czars d. Paideia Czars </span></p>
                     <p class="c96"><span class="c5">All other appointments shall be ratified by majority vote of the Senate. 3. In cases where an appointment to one of these positions must be made during Summer </span></p>
                     <p class="c51"><span class="c5">Recess, Winter Recess, or at any time when the Senate is not expected to meet within the following two weeks, the Student Body President shall make an interim appointment for these positions. The Student Body President should notify the Senate of all interim appointments as they happen, but shall also notify the Senate at the first regular meeting of the Senate following the date of interim appointment. 4. If the Student Body President makes an appointment without the recommendation of the </span></p>
                     <p class="c120 c179"><span class="c5">Senate Appointments Committee, s/he must notify the Senate at its next regular meeting, at which time the Senate may revoke the appointment by a two-thirds vote. If the Senate does not invalidate the appointment at that time, the Senate shall be considered to have approved the appointment. 5. The Student Body President shall be an </span><span class="c36">ex officio </span><span class="c5">non-voting member of all Senate-appointed </span></p>
                     <p class="c118"><span class="c5">Committees and Boards except the Judicial Board. </span></p>
                     <p class="c171"><span class="c2">B. Removal of Members of Student Committees and Boards </span></p>
                     <p class="c120 c160"><span class="c5">1. All </span><span class="c36">ex officio </span><span class="c5">appointments to Senate Committees or Boards shall be terminated automatically </span></p>
                     <p class="c40"><span class="c5">upon departure of the appointee from that office, whether by resignation, recall or expiration of term. 2. A Senate committee member may be removed only by majority vote of the Senate. Such a </span></p>
                     <p class="c29"><span class="c5">vote shall be based on the judgment that the member&#39;s performance has been egregious and unacceptable. </span></p>
                     <p class="c154"><span class="c2">C. Governance of Student Committees and Boards </span></p>
                     <p class="c120 c165"><span class="c5">1. Unless specified otherwise in this document or in its own bylaws, each committee or board </span></p>
                     <p class="c48"><span class="c5">shall choose its own chair. Meetings shall be called by the chair or at least one half of the voting members. Quorum shall be one half of the voting members. Decisions shall be rendered by majority vote of those present. 2. Committee bylaws and bylaw changes must be approved by the Senate to be valid. </span></p>
                     <p class="c49"><span class="c2">Section 3. Secretary </span></p>
                     <p class="c91"><span class="c2">A. Appointment of Secretary </span></p>
                     <p class="c120 c124"><span class="c5">1. The Student Body President, upon the recommendation of the Appointments Committee, shall appoint a Secretary no later than one week before the end of spring semester classes. This Secretary&rsquo;s term shall begin on the first day of classes of the next school year and run until the last day of classes of that year. 2. The Senate may dismiss the Secretary by a majority vote. The Student Body President shall </span></p>
                     <p class="c109"><span class="c5">then appoint a new Secretary. </span></p>
                     <p class="c88"><span class="c2">B. Responsibilities of the Secretary </span></p>
                     <p class="c120 c122"><span class="c5">1. The Secretary shall produce minutes of each official meeting of the Senate and make the </span></p>
                     <p class="c128"><span class="c5">approved minutes public. The minutes shall include, at the least: </span></p>
                     <p class="c59"><span class="c5">1. The date of the meeting 2. The names of those present 3. All motions recognized by the chair 4. A clear record of each Senator&rsquo;s vote in each vote taken. 2. The Secretary shall distribute a preliminary version of the minutes to all Senators before the next regular meeting of the Senate. The Senate may amend this preliminary version and approve it (by majority vote). The Secretary shall make public that part of the approved minutes which does not cover an executive session, by publication to the Senate website.. 3. </span><span class="c32">4. The Secretary shall maintain in the Executive Office a Senate Record. The Record shall </span></p>
                     <p class="c12"><span class="c5">contain all Senate minutes and SCAPP minutes up to the present, insofar as such documents are available. The Senate may, by a majority vote, direct the Secretary to include a document in the Record and the Secretary shall do so. The Secretary shall make these documents available to every Senator. At the end of the semester, the Secretary shall provide a copy of these documents to the incoming Secretary. 5. The Secretary shall, upon request of any Senator, deliver a letter or message regarding Senate </span></p>
                     <p class="c76"><span class="c5">business. Upon request of any Senator the Secretary shall type from a rough draft any document regarding Senate business. The Secretary may refuse to type or deliver any document which they may consider unrelated to Senate business. The Secretary shall be required to type or deliver a document if a majority of the Senate votes to do so at a meeting of the Senate. As part of this responsibility, the Secretary may be asked to update the Senate websites, Senate&rsquo;s social media pages, and bulletin board. </span></p>
                     <p class="c149"><span class="c2">Section 4. The Advocate of the Student Body </span><span class="c5">The Student Senate may initiate honor processes against members of the Student Body or the Community at large if by the unanimous consent of the voting members they feel sufficiently injured as a body to pursue such action. In such cases Senate shall appoint a representative to take action on behalf of Senate. The advocate for Senate shall report to Senate and follow the proper community grievance procedures. </span></p>
                     <p class="c26"><a name="sin-bylaws-article4">
                     <h2 class="rainbow-article-4">Article IV. Student Body Elections </h2>
                     </p>
                     <p class="c152"><span class="c2">Section 1. The Elections Czars and the Elections Bylaws </span></p>
                     <p class="c86"><span class="c5">A. Before the midpoint of each semester the Senate shall appoint at least one (1) enrolled Reed student to be Elections Czar(s). The term of office for the Elections Czar(s) shall end at the end of the semester of their appointment. B. Elections Czars shall not offer preferential treatment to or for any candidate running for office. C. The Elections Czar(s) shall be removed from the position either upon presentation of a signed resignation to the Student Body President, or upon approval by at least two-thirds (2/3) of the Senate of a motion to remove. D. The powers and duties of the Elections Czar(s) shall be as set forth in the Student Body Elections Bylaws. E. The Student Body Elections Bylaws shall define the procedures to be followed in each election for a student office. </span></p>
                     <p class="c18"><span class="c2">Section 2. Valid Elections </span><span class="c5">A. An election for any student office shall be considered valid if and only if the required number of students cast ballots in the election and the Senate accepts the results reported by the Elections Czar(s) in consultation with the SIN Webmaster. B. If an election for any student office is found not to be valid for any reason, then one (1) week shall be allowed for the nomination of the new candidates for the office, and another election shall be held in which the quorum shall be one (1). C. In the event, for whatever reason, the election&#39;s procedures are impossible to realize, the Senate may alter the procedures for the election at hand only. </span></p>
                     <p class="c164"><span class="c2">Section 3. Selection of President and Vice President of the Student Body and Student Senators </span><span class="c5">A. Nominations for the offices of Student Body President and Vice President and for three positions of Student Senator, to be chosen in accord with Article III of the Student Body Constitution, for the terms beginning at the conclusion of the fall semester shall be opened no later than one week after the Monday after Fall Break, and shall be due a minimum of two weeks later, leaving enough time for candidates to submit their statements to </span><span class="c36">The Quest</span><span class="c5">. B. Nominations for five positions of Student Senator, to be chosen in accord with Article III of the Student Body Constitution, for terms beginning at the conclusion of the spring semester shall be opened the Monday after Spring Break, and shall be due between two and three weeks later, leaving enough time for elections to occur before Renn Fayre. C. Nominations for the offices of President and Vice President shall be by petition of 50 members of the Student Body; those for Student Senator by petition of 25 members of the Student Body. D. The Elections Assembly shall be held on a weeknight following the closing of nominations. Balloting shall be conducted the week immediately following the Elections Assembly. E. The President, Vice President, and Student Senators shall take office at the conclusion of the semester in which they were elected, and serve a term of one year. Terms for newly-elected senators begin on the day immediately following the last day to submit written work (as determined by the Registrar). Terms for the newly-elected President and Vice President begin on the 15th of January. </span></p>
                     <p class="c117"><span class="c2">Section 4. Selection and Succession of Quest Editorial Board </span><span class="c5">A. The Quest Editorial Board shall be selected by the means outlined in the Quest Bylaws. </span></p>
                     <p class="c115"><span class="c2">Section 5. Replacement of Student Officers </span></p>
                     <p class="c22"><span class="c5">A. The Vice President of the Student Body shall immediately fill any vacancy of the Student Body Presidency, and shall serve until the next regular Presidential election. The Student Senate shall immediately choose a Senator to fill any vacancy of the Student Body Vice Presidency. The new Vice President shall resign from their office of Senator and serve as Vice President until the next regular election for that office. B. Vacancies in the office of Student Senator shall only be filled if at least one of the following two conditions is met: 1) the position becomes available on or before the Monday following the conclusion of Fall or Spring Break 2) the vacancy would result in fewer than six senators in office. If either or both of these conditions is met, the seat shall be immediately filled from among the unsuccessful candidates ranked higher than no quorum for these offices at the last regular election in the following manner: the candidate who received the highest vote total shall fill the first vacancy; the candidate with the next highest vote total shall fill the second vacancy, and so forth. Student Senators selected in this manner shall serve until the next regular election, whereupon new Senators shall be elected to fill the remainder of the terms. If there were no unsuccessful candidates ranked higher than no quorum for the office of Senator during the most recent regular election, then the vacancy shall be filled by a special election within two weeks of the resignation. If the position is vacated between semesters when school is not in session, the vacancy shall be filled by a special election held within two weeks of the resume of the next academic session. C. All special elections shall be governed by the rules applying to the regular election procedure for the office in question. </span></p>
                     <p class="c34"><a name="sin-bylaws-article5">
                     <h2 class="rainbow-article-5">Article V. The Student Committee on Academic Policy and Planning </h2>
                     </p>
                     <p class="c182"><span class="c2">Section 1. Functions </span><span class="c5">A. The Student Committee on Academic Policy and Planning (SCAPP) shall function as specified in the Reed College Community Constitution (Article V, Section 3), the Bylaws of the Constitution of the Faculty (Article IV, Section 3), the Student Body Constitution (Article V), and these Student Senate Bylaws.<br> B. SCAPP shall meet at least as often as CAPP regularly meets, typically no less than three times per month while school is in session. All SCAPP meetings shall be publicized and open to the Reed Community. </span></p>
                     <p class="c163"><span class="c2">Section 2. Composition </span><span class="c5">A. SCAPP shall consist of nine members of the Student Body. </span></p>
                     <p class="c46"><span class="c5">1. Three members of the committee shall be members of the Student Senate, who shall serve </span></p>
                     <p class="c106"><span class="c5">for terms of one semester. This member or these members shall report upon SCAPP meetings to the Student Senate. 2. The other members of the committee shall be appointed by the Senate, upon the </span></p>
                     <p class="c185"><span class="c5">recommendation of the Appointments Committee, for terms of one year. Appointments shall occur at the end of the semester before the next SCAPP term begins.
                     B. SCAPP shall appoint one or two chair(s) from among its members at the beginning of each semester for a term of one semester. The chair(s) shall call and preside at SCAPP meetings, attend signator training each semester and hold signatory authority for SCAPP funds, and fulfill other duties specified in the Reed College Community Constitution. C. SCAPP shall weekly choose two or three delegates to CAPP or faculty meetings from its members, one of whom shall be a chair. These delegates shall represent SCAPP at CAPP meetings, and shall report upon these meetings to SCAPP. </span></p>
                     <p class="c73"><a name="sin-bylaws-article6">
                     <h2 class="rainbow-article-6">Article VI. The Student Diversity Committee </h2>
                     </p>
                     <p class="c192"><span class="c2">Section 1. Functions </span><span class="c5">1) The mission of the Student Diversity Committee (hereafter, SDC) shall consist of three main endeavors, presented in order of importance: </span></p>
                     <p class="c7"><span class="c5">1. Represent student concerns about diversity to the administration and advocate for a more </span></p>
                     <p class="c122 c120"><span class="c5">pluralistic curriculum 2. Ensure that diversity is relevant to the processes and principles of student governance at </span></p>
                     <p class="c6"><span class="c5">Reed 3. Coordinate with other campus groups to foster mindfulness and inclusivity of different </span></p>
                     <p class="c181"><span class="c5">voices 2) Once a semester, the SDC shall present a report at an open Senate meeting. This report will include suggestions for any initiatives the SDC believes the Student Senate should undertake around issues of diversity among the student body and institutional practices of the college. 3) The SDC shall meet at least once every week while school is in session, All SDC meetings shall be publicized and open to the Reed community. 4) Once a semester, the SDC shall meet with the Committee on Diversity, to discuss issues of diversity effecting both communities, and any initiatives that the SDC or Committee on Diversity have put forth. </span></p>
                     <p class="c166"><span class="c2">Section 2. Composition </span><span class="c5">1) The SDC shall consist of six members of the Student Body </span></p>
                     <p class="c137 c120"><span class="c5">1. One member of the committee shall be a member of the Student Senate, who shall serve for </span></p>
                     <p class="c106"><span class="c5">one semester. 2. The other members of the committee shall be appointed by the Senate, upon the </span></p>
                     <p class="c60"><span class="c5">recommendation of the Appointments Committee, for terms of one year. 3. Appointments shall occur at the beginning of each semester and be staggered. It should be </span></p>
                     <p class="c178"><span class="c5">the goal of Appointments Committee that the SDC reflect the full spectrum of student body opinions on issues of diversity and inclusion. 2) SDC shall appoint a chair from among its members at the beginning of each semester for a term of one year. The chair shall call and preside at SDC meetings. </span></p>
                     <p class="c172"><a name="sin-bylaws-article7">
                     <h2 class="rainbow-article-7">Article VII. Rules and Procedures for Meetings </h2>
                     </p>
                     <p class="c61"><span class="c2">Section 1. Rules for Meetings </span><span class="c5">A. Meetings shall be conducted according to Robert&rsquo;s Rules of Order and in accordance with these bylaws. B. Senate shall meet once a week, and the time of Senate meetings shall be advertised to the general Reed community. C. The President of the Senate shall lead all meetings unless they are unavailable in which case the Vice President shall act as the President pro-tempore. </span></p>
                     <p class="c196"><span class="c2">Section 2. Executive Session </span><span class="c5">A. A majority vote of the Senate is required to enter an executive session except in those instances where executive session is mandated by these bylaws. B. Executive session shall be used to discuss matters and to communicate information, which, in a public setting, would have the possible consequence of making an individual or group suffer unnecessary harm or discomfort. These matters include, but are not limited to: </span></p>
                     <p class="c120 c189"><span class="c5">1. Those concerning potential, present, or previous personnel, including but not limited to </span></p>
                     <p class="c168"><span class="c5">senators, elected officials, Senate&rsquo;s appointees, and signators; 2. Honor Cases or other matters pertaining to Senate&rsquo;s business with the Judicial Board; and C. Matters in which confidentiality is required by duly enacted community documents and policies, and local, state, and federal law. D. All proceedings held in executive session in person and electronically are considered confidential and shall not be discussed with members of the community who were not invited to participate in the executive session. A violation of executive session privilege shall be considered a violation of the honor principle. </span></p>
                     <p class="c142"><a name="sin-bylaws-article8">
                     <h2 class="rainbow-article-8">Article VIII. Amendment and Suspension of Bylaws </h2>
                     </p>
                     <p class="c35"><span class="c2">Section 1. Amendment of Senate Bylaws </span><span class="c5">These bylaws may be amended only by two-thirds (2/3) vote of the Senate. The date the amendment passed shall be recorded at the top of this document. The newly amended bylaws shall be made available in all computer and hard copy locations such documents are stored. The Secretary shall be responsible for maintenance of such records, as outlined in Article III, Section 3, Part C(iii). </span></p>
                     <p class="c105"><span class="c2">Section 2. Suspension of Senate Bylaws </span><span class="c5">These bylaws, in part or in full, may be suspended by a two-thirds (2/3) vote of the full Senate for a specified period of time. These bylaws, in part or in full, shall be reinstated at any time by a two- thirds (2/3) vote of the full Senate. </span></p>
                  </div>
               </div>
               <div class="col-0 col-md-1"></div>
            </div>
         </div>
      </section>
      <?php include '../pagelets/footer.php'; ?>
   </body>
</html>