---
title: "Webmaster Manual"
output: pdf_document
header-includes:
  - \newcommand{\note}{\textbf{Note:}}
  - \newcommand{\example}{\textbf{Example:}}
  - \newcommand{\config}{const \textit{ CONFIG}}
---

# Tools Used

1. GoDaddy (Ask Reed Treasury for login details)
2. Firebase 
3. Github

Here is a table of contents for the manual, along with a short description of each section.

# Table of Contents

1. Structure: runs through how to abstractly think about what the website "is" and what role each component plays.

2. Database collections: goes through the details of what role each database collection plays inter-relationally and independently.

3. Maintainence and Event Running: explains the procedures Webmasters will routinely do to maintain the website and run the semester's funding poll and the elections.

# Structure

The "website" effectively works by maintaining and ensuring the health of two interplaying elements:

a. Website codebase

The website source files are files found in the website directory, which can be found by logging on the GoDaddy website and accessing the file directory through cPanel.

b. Firebase database 

The other element is the website-specific Firebase database collections. Firebase is a service provided by Google that hosts databases which has pre-exisiting infastructure for read/write abilities on data the website utilizes.

\newpage

# Database collections 

There are 7 primary database collections, and they are listed below along with a short functional description.

## Collections Breakdown

### Collections

a. elections: event-indexed collections of the past and current student body election.
b. polls: event-indexed collections of the past and current funding poll.
c. nominations: dataset array containing nominee-submitted information about each candidate.
d. users_who_have_voted: event-indexed collections of the users who have voted in the funding polls and elections.
e. signatories: semester-dependent collection of all currently approved signators.
f. registered_clubs: semester-dependent collection of all currently registered clubs.
g. fund_requests: semester-dependent collection of all the signator-submitted funding requests. 

The database collections may be partioned into two primary subsets. The semester dependent subset and the non-semester dependent subset.

### Semester dependent

a. signatories
b. registered_clubs
c. fund_requests

$\note$ Every semester dependent collection has a subcollections which are named the semester-specific strings. For continuity, please ensure the string takes the form: $[semester] = \textit{term-year}$. 

$\example$ The string name for the any semester dependent subcollection for the Fall 2020 semester is $[\textit{fall-2020}]$.

### Event-indexed (Non-semester depdendent)

a. elections
b. polls
c. users_who_have_voted
d. nominations

$\note$ We can also name the non-semester depedent collections the set of event-indexed collections. The reason is because every subcollection in these collections has a name which takes the form: 
$$\textit{event-[semester]-SHA32id}$$
1. The event is a two letter index of whether the event is a funding poll $(fp)$ or an SB election $(se)$. \newline
2. The semester is simply the string as explained above, as follows: $[semester] = \textit{term-year}$. \newline
3. Lastly, the SHA32 index is simply a random SHA32 hash that uniquely identifies every (semester, event) pair. \newline

$\example$ The funding poll happening in Fall 2020 with a SHA32 ID of ABC will be: $\textit{fp-fall-2020-ABC}$.

For continuity, please ensure every event-indexed collection has subcollection names which take the form: $\textit{event-[semester]-SHA32id}$. 

\newpage

## Event and collections relations

The relation between these collections and events is given by: ${event} \leftarrow \{collections\}$. 

a. Funding Poll $\leftarrow$ $\{$users_who_have_voted, registered_clubs$\}$
b. Elections $\leftarrow$ $\{$users_who_have_voted, nominations, elections$\}$

Different utilities/classes on the website utilize different subsets of these collections. The utility-collection subsets pairs are given below. We say that a utility $\textbf{talks}$ with a subset of database collections if the website codebase is programmed to have a read-write relationship between that utility and the collections in that subset.  

## Funding-poll 

Funding-poll $\textbf{talks}$ to the subset:

a. registered_clubs: show club information and edit the votes entry in the club array (read/write)
b. users_who_have_voted: keeps track of users who have voted in the current event. (read/write)

## Election

Election-class $\textbf{talks}$ to the subset:

a. campaigns: read in the blurbs of each candidate (read)
b. users_who_have_voted: keeps track of users who have voted in the current event. (read/write)

## Dash-door

Dash-door $\textbf{talks}$ to the subset:

a. signatories: add and view current semester's signatories (read/write)
b. registered_clubs: view current semester's clubs information (read)
c. fund_requests: view funding requests (read)
d. elections: view current campaign data (read)

\newpage

# Maintainence and Event Running Routines

## Updating the Website (R1)

Updating the website may be tricky at first but it should be easy once the Webmaster does a few practice tries. The standard routine of updating the website should $\textbf{NOT}$ involve directly editing the files on cPanel. Doing so will create some large issues with Github version control in the future. Instead, please use Git or install Github Desktop (more user-friendly) and have a local copy of the website directory installed. Then, the Webmaster may edit the repository and propogate the changes through Github. 

Suppose the Webmaster implements changes to a local copy of the website on their device. Once the changes are done, the Webmaster should build the $\textit{app.min.js}$ script if $\textit{app.js}$ is edited. Otherwise, push the changes onto the Github Repository. Then, log on to the GoDaddy website, and find the cPanel Adminstrator Panel. Then, go to 'Github Version Control' $\rightarrow$ 'Manage' $\rightarrow$ 'Pull and Deploy'. Pressing 'Update from Remote' should update the website.

## Subroutine: Building the Script

To build the $\textit{app.min.js}$ script, proceed to the directory containing $\textit{build.sh}$. On terminal, execute the script by writing:
$$\textit{bash build.sh}$$

## Semester Changes (R2)

Before every semester begins, change the $\config$ expression in $\textit{app.js}$ to reflect the current semester. Then, ensure every semester dependent collection has a collection pertaining to the new semester. Note that $\textbf{this must be done manually}$ by the Webmaster(s). Recall that the semester name must follow the form:
$$[semester] = \textit{term-year}$$

For reference, these are the semester dependent collections:

### Semester dependent

a. signatories
b. registered_clubs
c. fund_requests

## Detailed Instructions

Here are more direct instructions for the semester change routine. The process should be clearer once the Webmaster explores the collections of previous semesters. Implementation of the new semesters should not be any different. 

1. In $\textit{app.js}$, the main code file, find the $\config$ expression and rename the semester to the current $[semester]$ string.
2. In Firebase, go to each semester-dependent collection and add a new collection for that semester using the exact same $[semester]$ string.
3. Then, within each collection, create an $\textbf{empty}$ array with the same name as that master collection. For example, if you are updating $signatories$, you will create a new empty $signatories$ array in the new semester collection. 
4. Update the website as in Routine 1 (R1).

## Dashdoor Permissions

Every semester, Reed Treasury rotates and adds new members. These new members will ask for permission to Dashdoor, the adminstrative backdoor of the website. To give those users permission, you must edit the $\config$ and add the relevant emails to the 'authorised_users' array. Then, remember to build the script and update the website as in Routine 1.

\newpage

$\note$ The funding poll and student body elections applets do not seem to be functional as of Fall 2020. Also worth noting is that the parameter $direct_server_load$ in the $\config$ file seems to crash the website when set to $false$.

## Running Funding Poll

Some manual steps are necessary to run a funding poll event. 

1. Edit the time parameters $\textit{fpopens}$ and $\textit{fpcloses}$ in the $\config$ to ensure funding poll is open and closed at the right times. These parameters are determined by the Treasury.

2. Change the $\textit{poll-name}$ entry in the $\config$ file to reflect the current funding poll ID. Recall that it must follow the form:
$$\textit{fp-[semester]-SHA32id}$$

## Running Student Body Elections

1. Edit the time parameters $\textit{seopens}$ and $\textit{secloses}$ in the $\config$ to ensure that the SB elections is open and closed at the right times. These parameters are determined by the Senate.

2. Change the $\textit{secampaign}$ entry in the $\config$ file to reflect the current senate election ID. Recall that it must follow the form:
$$\textit{se-[semester]-SHA32id}$$